# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schedule/schedule.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'schedule/schedule.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17schedule/schedule.proto\x1a\x1egoogle/protobuf/wrappers.proto\"<\n\x0fScheduleRequest\x12\r\n\x05group\x18\x01 \x01(\x03\x12\r\n\x05\x62\x65gin\x18\x02 \x01(\t\x12\x0b\n\x03\x65nd\x18\x03 \x01(\t\"\x89\x01\n\x04Pair\x12\x0c\n\x04time\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x13\n\x0blesson_name\x18\x03 \x01(\t\x12\x0f\n\x07teacher\x18\x04 \x01(\t\x12\x10\n\x08\x61udience\x18\x05 \x01(\t\x12-\n\x08subgroup\x18\x06 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\" \n\x08PairList\x12\x14\n\x05items\x18\x01 \x03(\x0b\x32\x05.Pair\"x\n\x07\x44\x61yData\x12\x10\n\x08\x64\x61y_week\x18\x01 \x01(\t\x12\"\n\x05pairs\x18\x02 \x03(\x0b\x32\x13.DayData.PairsEntry\x1a\x37\n\nPairsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x18\n\x05value\x18\x02 \x01(\x0b\x32\t.PairList:\x02\x38\x01\"\x80\x01\n\x10ScheduleResponse\x12\x31\n\x08schedule\x18\x01 \x03(\x0b\x32\x1f.ScheduleResponse.ScheduleEntry\x1a\x39\n\rScheduleEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x17\n\x05value\x18\x02 \x01(\x0b\x32\x08.DayData:\x02\x38\x01\x32\x45\n\x0fScheduleService\x12\x32\n\x0bGetSchedule\x12\x10.ScheduleRequest\x1a\x11.ScheduleResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schedule.schedule_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DAYDATA_PAIRSENTRY']._loaded_options = None
  _globals['_DAYDATA_PAIRSENTRY']._serialized_options = b'8\001'
  _globals['_SCHEDULERESPONSE_SCHEDULEENTRY']._loaded_options = None
  _globals['_SCHEDULERESPONSE_SCHEDULEENTRY']._serialized_options = b'8\001'
  _globals['_SCHEDULEREQUEST']._serialized_start=59
  _globals['_SCHEDULEREQUEST']._serialized_end=119
  _globals['_PAIR']._serialized_start=122
  _globals['_PAIR']._serialized_end=259
  _globals['_PAIRLIST']._serialized_start=261
  _globals['_PAIRLIST']._serialized_end=293
  _globals['_DAYDATA']._serialized_start=295
  _globals['_DAYDATA']._serialized_end=415
  _globals['_DAYDATA_PAIRSENTRY']._serialized_start=360
  _globals['_DAYDATA_PAIRSENTRY']._serialized_end=415
  _globals['_SCHEDULERESPONSE']._serialized_start=418
  _globals['_SCHEDULERESPONSE']._serialized_end=546
  _globals['_SCHEDULERESPONSE_SCHEDULEENTRY']._serialized_start=489
  _globals['_SCHEDULERESPONSE_SCHEDULEENTRY']._serialized_end=546
  _globals['_SCHEDULESERVICE']._serialized_start=548
  _globals['_SCHEDULESERVICE']._serialized_end=617
# @@protoc_insertion_point(module_scope)
